services:
  - type: web
    name: pingme-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 